<a href="https://colab.research.google.com/github/seusik1122/2024-OSS/blob/main/3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.adarray(shape=(2,2), dtype=int)
a

AttributeError: module 'numpy' has no attribute 'adarray'

In [ ]:
import numpy as np

a= np.array([1,2,3], dtype=int)
a

array([1, 2, 3])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
print(a.shape)
print(a.ndim)
print(a.dtype)

(3,)
1
int64


In [ ]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


In [ ]:
a.data

In [ ]:
import numpy as np

np.array(1,2,3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [ ]:
np.array([1, 'py', 3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [ ]:
import numpy as np

unicode_array = np. array(['가나다', '라마바', '사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [ ]:
lang = np.array(['파이썬', '자바', '씨'])
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [ ]:
lang = np.array(['파이썬', '자바', '씨'], dtype = str)
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [ ]:
a = np.array((1,2,3), dtype=float)
a

array([1., 2., 3.])

In [ ]:
b = np.array((1, 2.5, 3))
b

array([1. , 2.5, 3. ])